### ISSUE TITLE
Edge rtl text goes off buckets

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/isotopes-and-atomic-mass#91]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Edge
**Problem description:**
For https://github.com/phetsims/QA/issues/300
This does not occur in the published version.  Only seen on edge so far.  When string test is rtl, the text on the buckets holding isotopes on the second screen goes off center and runs off the edge of the bucket.  Since the text and background are both white this may be a more significant problem.  Seen on both my mix and nature mix.
**Steps to reproduce:**
1. Set stringTest=rtl on sim in Edge
2. Go to the second screen
3. Select an atom and look at the isotope buckets

**Screenshots:**
![edgebucketsoff](https://user-images.githubusercontent.com/41024075/55644681-de20a080-5793-11e9-9370-58c3cec4581e.png)

**Troubleshooting information (do not edit):**

<details>

Name: ‫تست (زبان)‬
URL: https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.0-rc.1/phet/isotopes-and-atomic-mass_en_phet.html?stringTest=rtl
Version: 1.1.0-rc.1 2019-03-22 21:49:06 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
Language: en-US
Window: 1536x751
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Microsoft (Microsoft Edge)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
More noticeable the more buckets there are.

**Comment by KatieWoe** [comment]
The labels on the sliders are off center as well.

**Comment by arouinfar** [comment]
This looks a bit odd to me, can you investigate @jbphet?

**Comment by KatieWoe** [comment]
Not in IE on same device

**Comment by KatieWoe** [comment]
@ariel-phet and @jbphet depending on how long this fix takes and how long it takes edge to switch to chromium, this may not be worth addressing.  I did a check of this on the dev version of edge and the problem did not show up.  I don't believe it showed up anywhere else that was tested.

**Comment by jbphet** [comment]
Since this is an unusual situation, i.e. and RTL language being used in Edge, and will likely be fixed in Edge soon, I think it isn't worth much of an investment of time and effort to investigate and fix.  Assigning to @ariel-phet to make sure he concurs.

**Comment by ariel-phet** [comment]
@jbphet I concur...not worth the effort. 

Marking as `wontfix`

**Comment by jbphet** [comment]
Closing.

**Comment by KatieWoe** [comment]
Making a note that as of testing https://github.com/phetsims/QA/issues/310 Edge has not updated and this issue is still present.
